---
# tasks file for cmake_checks

- name: Install cmake and dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  loop:
    - cmake
    - clang
    - lld
  become: true
  when: ansible_os_family == 'Debian'