---
# tasks file for psql_checks
- name: Install psql CLI tool to interact with postgres
  ansible.builtin.apt:
    name: postgresql-client-common
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: true
  when: ansible_os_family == 'Debian'